Publish JUnit results

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,53 +1,58 @@
 ---
 name: Test
 on:
-    pull_request:
-        types:
-            - opened
-            - synchronize
-            - reopened
-    push:
-        branches:
-            - main
-        tags:
-            - "*"
+  pull_request:
+    types:
+      - opened
+      - synchronize
+      - reopened
+  push:
+    branches:
+      - main
+    tags:
+      - "*"
 jobs:
-    docker-image:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-            - name: Build docker image
-              run: docker build . -t adventofcode:test
-            - env:
-                  AOC_SESSION: ${{ secrets.AOC_SESSION }}
-              name: Smoke test docker image
-              run: |
-                  docker run --rm -e AOC_SESSION adventofcode:test
-    test:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-              with:
-                  fetch-depth: 0
-            - name: Install poetry
-              run: pipx install poetry
-            - name: Setup Python
-              uses: actions/setup-python@v4
-              with:
-                  cache: poetry
-                  python-version: "3.10"
-            - name: Install dependencies with poetry
-              run: poetry install
-            - uses: chartboost/ruff-action@v1
-            - run: poetry run black --check .
-            - run: poetry run mypy
-            - run:
-                  poetry run pytest --cov --cov-report=xml:coverage.xml
-                  --junitxml=junit.xml
-              env:
-                  AOC_SESSION: ${{ secrets.AOC_SESSION }}
-            - name: SonarCloud Scan
-              uses: SonarSource/sonarcloud-github-action@master
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
-                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  docker-image:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Build docker image
+        run: docker build . -t adventofcode:test
+      - env:
+          AOC_SESSION: ${{ secrets.AOC_SESSION }}
+        name: Smoke test docker image
+        run: |
+          docker run --rm -e AOC_SESSION adventofcode:test
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Install poetry
+        run: pipx install poetry
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          cache: poetry
+          python-version: "3.10"
+      - name: Install dependencies with poetry
+        run: poetry install
+      - uses: chartboost/ruff-action@v1
+      - run: poetry run black --check .
+      - run: poetry run mypy
+      - run:
+          poetry run pytest --cov --cov-report=xml:coverage.xml
+          --junitxml=junit.xml
+        env:
+          AOC_SESSION: ${{ secrets.AOC_SESSION }}
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          report_paths: "**/junit.xml"
